name: CD Pipeline for Deployment

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Static Website
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build static website using Parcel
      - name: Build website
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"
      
      # Upload build artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dev"  # The build output folder

  deploy-develop-job:
    name: Deploy to GitHub Pages
    needs: build  # Ensure the deploy step runs after the build
    environment: development-env
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
